### ISSUE TITLE
Fastreid config

### ISSUE THREAD

**Issue by gtfaiwxm** [fubel/synthehicle#1]
Hi, can you give me a fastreid config of vechile ReID? Thanks!

**Comment by fubel** [comment]
You can create a config similar to this, e.g., for a Bag of Tricks baseline:

```
_BASE_: ../Base-bagtricks.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True
    WITH_NL: True

DATASETS:
  NAMES: ("Synthehicle",)
  TESTS: ("Synthehicle",)

DATALOADER:
  SAMPLER_TRAIN: NaiveIdentitySampler

TEST:
  EVAL_PERIOD: 40
  IMS_PER_BATCH: 256

SOLVER:
  MAX_EPOCH: 120
  BASE_LR: 0.00025
  STEPS: [30, 50]
  WARMUP_ITERS: 2000

OUTPUT_DIR: logs/synthehicle/bag_of_tricks
```

You need to specify a `Synthehicle` dataset class in fastreid, which you can essentially copy from their `VeRi` class and change the paths accordingly. We will soon be sharing our configs for re-identification as well as the cropped bounding boxes used for re-id training.
